### ISSUE TITLE
missing audio on most Lua talks

### ISSUE THREAD

**Issue by Habbie** [FOSDEM/videobox#12]
I checked ~5 videos in http://video.fosdem.org/2016/k3201/ and except for `the-future-of-small-languages.mp4` I got no audio. Please tell me it is still coming :)

**Comment by Thulinma** [comment]
It is coming - the wrong audio channel was encoded. I can confirm audio **was** recorded that day.
(To be specific - the external mic was plugged into the right channel instead of the left - causing the encoder to throw away the wrong channel by default.)

Re-encodes with the correct channel will follow shortly. Probably tomorrow.

**Comment by Habbie** [comment]
Thanks, this is a relief. I'll wait :)

**Comment by boegel** [comment]
I did the cutting for the Lua devroom, the sound *is* there (I heard it when cutting).

We tried to fix this, but apparently the encoding didn't pick up on it like it should have.

**Comment by Habbie** [comment]
Appears to be all solved. Thanks for the effort, folks! Closing this ticket.
