### ISSUE TITLE
even better sync between slides and cam (currently 6 sec max) 

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/videobox#2]

**Comment by Thulinma** [comment]
Judging from the footage so far, it looks like the current syncing method is no longer ~6s max out of sync, but more in the area of 1-2s.
This is mostly caused because we're noting everything in (whole) seconds now, and the 1-2s desync are rounding errors.
Proper storage inside the boxes next year should fix this (with ms-accuracy footage seeking).

**Comment by Thulinma** [comment]
Accuracy has since been improved in the system internals, and any delays next year should now be purely hardware-related. Yay!
