### ISSUE TITLE
Missing video : Hacking on the Fairphone 2

### ISSUE THREAD

**Issue by alexisju** [FOSDEM/videobox#42]
The video of [the conference about the Fairphone 2](https://fosdem.org/2016/schedule/event/fairphone2/) still not available in http://video.fosdem.org/2016/ud2120/

**Comment by sphaero** [comment]
Still not available indeed: 
http://video.fosdem.org/2016/ud2120/STATUS.TXT:
```
OK: NOT AVAILABLE YET - WILL BE FIXED ASAP (4328.txt) - 'Hacking on the Fairphone 2'
```

**Comment by teufli** [comment]
FOSDEM staff: Could you please upload the raw, unedited material?

**Comment by Thulinma** [comment]
Policy is not to release unedited material because people will have been recorded not realizing they were being recorded.
Rest assured however, that all missing videos will be uploaded very soon. On June 11th most of the video team is getting together for specifically the purpose of getting the last few things finished up.

**Comment by teufli** [comment]
Thank you for your work, the video is available now. :+1:

**Comment by Thulinma** [comment]
Sorry for the long wait, but indeed, now nearly all videos are finally available. :-)
